### ISSUE TITLE
Annotation do not work (Vue 3, Vite 5)

### ISSUE THREAD

**Issue by martinpokorny** [randolphtellis/vue3-pdfjs#22]
Hello, when I attempt to enable annotations by just following the basic example, I get following series of errors:

```
Uncaught (in promise) TypeError: this.linkService.getDestinationHash is not a function
    at LinkAnnotationElement._bindLink (annotation_layer.js:652:34)
    at LinkAnnotationElement.render (annotation_layer.js:601:12)
    at AnnotationLayer.render (annotation_layer.js:2566:34)
    at index-19f89c12.js:1474:48

Uncaught (in promise) TypeError: linkService.addLinkAttributes is not a function
    at LinkAnnotationElement.render (annotation_layer.js:595:19)
    at AnnotationLayer.render (annotation_layer.js:2566:34)
    at index-19f89c12.js:1474:48
```

On repeat for each present link in the loaded PDF. For now I just disabled annotations, as they are not critical for my use-case, but I am wondering what could be the source of the issues, and if somebody managed to fix this?

Running on Vue 3.0.7 with Vite 5.0 build stack, using Options API.

Thank you very much for your time.

**Comment by sicaifang** [comment]
I had the same problem。

![Image](https://github.com/user-attachments/assets/89506a40-679f-4269-a04c-c49492360442)
